In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_iris

In [8]:
df = load_iris()
y = df.target

In [5]:
x= df.data

In [6]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=143)

In [10]:
from sklearn import tree

In [11]:
clf = tree.DecisionTreeClassifier()

In [12]:
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [13]:
y_pred = clf.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [15]:
print(confusion_matrix(y_test,y_pred))

[[18  0  0]
 [ 0 13  0]
 [ 0  3 16]]


In [18]:
print( "Accuracy of the Decision tree:", accuracy_score(y_test, y_pred))

Accuracy of the Decision tree: 0.94
